# Generated by Django 3.0.3 on 2020-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('unitSize', models.CharField(max_length=100)),
                ('weightGrams', models.IntegerField()),
            ],
        ),
    ]
