# Generated by Django 3.0.3 on 2020-12-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('store', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('unitSize', models.CharField(max_length=100)),
                ('weightGrams', models.PositiveIntegerField()),
                ('lowStockLevel', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unitID', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ssh', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('stockControl_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('timeAdded', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Unit'),
        ),
    ]
