# Generated by Django 3.0.3 on 2020-12-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CR',
            fields=[
                ('crID', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('conversion', models.IntegerField()),
                ('barcode', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Product')),
            ],
        ),
    ]
