# Generated by Django 3.0.3 on 2020-12-10 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='timeAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
