# Generated by Django 3.0.3 on 2020-12-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20201210_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cr',
            name='barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Product'),
        ),
    ]
