# Generated by Django 3.0.3 on 2020-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_product_lowstocklevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('UnitID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('SSH', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='lowStockLevel',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='weightGrams',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('stockControlId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('barcode', models.ManyToManyField(to='mainApp.Product')),
            ],
        ),
    ]
