# Generated by Django 3.0.3 on 2020-11-20 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20201120_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='unit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Unit'),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='location',
            field=models.ManyToManyField(to='mainApp.Location'),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='UnitID',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
