# Generated by Django 3.0.3 on 2020-11-20 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20201120_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='SSH',
            new_name='ssh',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='UnitID',
            new_name='unitID',
        ),
        migrations.AddField(
            model_name='location',
            name='barcode',
            field=models.ManyToManyField(to='mainApp.Product'),
        ),
        migrations.AddField(
            model_name='location',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='timeAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StockControl',
        ),
    ]
