# Generated by Django 3.0.3 on 2020-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20201120_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='location',
            name='timeAdded',
        ),
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('stockControlId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('timeAdded', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.ManyToManyField(to='mainApp.Product')),
                ('location', models.ManyToManyField(to='mainApp.Location')),
            ],
        ),
    ]
