# Generated by Django 3.0.3 on 2020-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20201124_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcontrol',
            name='id',
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='stockControlId',
            field=models.IntegerField(auto_created=True, default=11, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
