# Generated by Django 3.0.3 on 2020-11-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20201124_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='stockControlId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
