# Generated by Django 3.0.3 on 2020-11-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20201124_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcontrol',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Product'),
        ),
    ]
