# Generated by Django 3.0.3 on 2020-12-09 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20201124_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcontrol',
            name='id',
        ),
        migrations.AddField(
            model_name='location',
            name='store',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='stockcontrol',
            name='stockControl_id',
            field=models.IntegerField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockcontrol',
            name='barcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Product'),
        ),
    ]
